export type HiraganaMnemonic = {
  emoji: string;
  title: string;
  story: string;
};

export const HIRAGANA_MNEMONICS: Record<string, HiraganaMnemonic> = {
  "あ": { emoji: "🐣", title: "Anak ayam berkata aaa", story: "Anak ayam membuka paruhnya lebar-lebar dan bersuara 'aaa'. Lengkung tubuh serta paruhnya berubah menjadi あ." },
  "い": { emoji: "👫", title: "Dua orang berdiri berdampingan", story: "Dua orang kurus berdiri sejajar sambil berkata 'ii'. Dua sosok itu membentuk dua coretan い." },
  "う": { emoji: "👄", title: "Mulut berbentuk U", story: "Mulut kecil mengucapkan 'u'. Bibir dan gerak suaranya berubah menjadi う." },
  "え": { emoji: "🧗", title: "Pendaki mencapai puncak", story: "Seorang pendaki berseru 'eh!' saat tali dan jalurnya membentuk え." },
  "お": { emoji: "🏌️", title: "Orang mengayun tongkat", story: "Orang mengayun tongkat sambil berseru 'o!'. Tubuh, tongkat, dan bola kecilnya membentuk お." },
  "か": { emoji: "🎣", title: "Kail menangkap ikan", story: "Sebuah kail besar menarik ikan. Kail dan tali yang menegang membentuk か untuk bunyi 'ka'." },
  "き": { emoji: "🔑", title: "Kunci dengan tiga gigi", story: "Sebuah kunci memiliki tiga gigi dan gagang melengkung. Kunci itu menjadi き, dibaca 'ki'." },
  "く": { emoji: "🐦", title: "Paruh burung terbuka", story: "Paruh burung terbuka seperti sudut tajam sambil berbunyi 'ku'. Siluet paruhnya adalah く." },
  "け": { emoji: "⚔️", title: "Kesatria membawa pedang", story: "Kesatria berdiri dengan pedang dan perisai. Garis perlengkapannya berubah menjadi け, bunyinya 'ke'." },
  "こ": { emoji: "🐟", title: "Dua ikan koi", story: "Dua ikan koi berenang sejajar. Dua jalur renangnya membentuk こ untuk bunyi 'ko'." },
  "さ": { emoji: "🏇", title: "Sadel di punggung kuda", story: "Sadel dan tali pada punggung kuda melengkung menjadi さ. Ingat 'sa' dari sadel." },
  "し": { emoji: "🎣", title: "Kail yang sangat panjang", story: "Kail panjang turun lalu melengkung seperti し. Seorang pemancing berbisik 'shi' agar ikan tidak lari." },
  "す": { emoji: "🍣", title: "Tusuk sushi berputar", story: "Tusuk menembus sushi lalu berputar membentuk simpul. Gerakannya menjadi す, awal dari 'sushi'." },
  "せ": { emoji: "🪡", title: "Jarum menjahit setelan", story: "Jarum dan benang menjahit sebuah setelan. Benang yang menyilang membentuk せ untuk bunyi 'se'." },
  "そ": { emoji: "🧵", title: "Benang yang tersangkut", story: "Seutas benang turun berkelok setelah tersangkut. Jalurnya membentuk そ untuk bunyi 'so'." },
  "た": { emoji: "🪑", title: "Tata meja dan kursi", story: "Meja, kursi, dan kaki-kakinya ditata hingga membentuk た. Ingat 'ta' dari tata." },
  "ち": { emoji: "💃", title: "Pemandu sorak berputar", story: "Pemandu sorak mengangkat tangan lalu memutar pita. Gerak tubuhnya berubah menjadi ち, dibaca 'chi'." },
  "つ": { emoji: "🌊", title: "Gelombang tsunami", story: "Satu gelombang besar tsunami melengkung ke pantai. Lengkung itu membentuk つ, dibaca 'tsu'." },
  "て": { emoji: "✋", title: "Tangan yang terbuka", story: "Sebuah tangan atau 'te' dalam bahasa Jepang direntangkan. Garis telapak dan jarinya membentuk て." },
  "と": { emoji: "🦶", title: "Jari kaki menyentuh tongkat", story: "Jari kaki atau toe menyentuh tongkat kecil. Keduanya berubah menjadi と untuk bunyi 'to'." },
  "な": { emoji: "🪢", title: "Tali membuat simpul", story: "Tali berputar menjadi simpul yang rumit. Ujung dan simpulnya membentuk な, dibaca 'na'." },
  "に": { emoji: "🦵", title: "Dua lutut sejajar", story: "Dua lutut atau knee terlihat sebagai dua garis di samping kaki. Bentuknya menjadi に, dibaca 'ni'." },
  "ぬ": { emoji: "🍜", title: "Mi melingkar di mangkuk", story: "Mi atau noodle berputar dan menyisakan ekor panjang. Putarannya membentuk ぬ, dibaca 'nu'." },
  "ね": { emoji: "🥅", title: "Jaring dengan simpul", story: "Sebuah net memiliki tiang, lilitan, dan simpul di ujung. Siluetnya membentuk ね, dibaca 'ne'." },
  "の": { emoji: "🚫", title: "Tanda larangan bulat", story: "Satu garis menggambar tanda 'no' yang bulat tanpa berhenti. Lingkarannya adalah の." },
  "は": { emoji: "😂", title: "Wajah tertawa ha-ha", story: "Wajah dengan dua mata tertawa 'ha-ha'. Garis wajah dan air matanya berubah menjadi は." },
  "ひ": { emoji: "😊", title: "Senyum lebar di wajah", story: "Sebuah wajah menarik senyum panjang sambil berkata 'hii'. Lengkung senyumnya membentuk ひ." },
  "ふ": { emoji: "🗻", title: "Gunung Fuji tertiup angin", story: "Angin berembus di atas Gunung Fuji dan memecah salju menjadi titik-titik. Bentuknya menjadi ふ, dibaca 'fu'." },
  "へ": { emoji: "⛰️", title: "Bukit menuju puncak", story: "Jalur naik lalu turun melewati puncak bukit. Jalur sederhana itu membentuk へ, dibaca 'he'." },
  "ほ": { emoji: "⛵", title: "Tiang dan dua layar", story: "Tiang kapal berdiri di samping dua layar. Semuanya membentuk ほ untuk bunyi 'ho'." },
  "ま": { emoji: "🗺️", title: "Peta dengan penanda", story: "Sebuah map memiliki dua jalan dan penanda melingkar. Garisnya berubah menjadi ま, dibaca 'ma'." },
  "み": { emoji: "🎼", title: "Not musik berkelok", story: "Nada musik melompat dan berkelok di paranada. Alurnya membentuk み, dibaca 'mi'." },
  "む": { emoji: "🐄", title: "Sapi berkata muu", story: "Seekor sapi mengangkat ekor dan berkata 'muu'. Tubuh serta ekornya berubah menjadi む." },
  "め": { emoji: "👁️", title: "Mata dengan garis silang", story: "Sebuah mata atau 'me' dalam bahasa Jepang dilintasi pantulan cahaya. Bentuknya menjadi め." },
  "も": { emoji: "🎣", title: "Kail membawa dua ikan", story: "Kail membawa dua ikan kecil dan meminta 'more'. Tali serta dua ikannya membentuk も." },
  "や": { emoji: "⛵", title: "Yacht dengan layar", story: "Sebuah yacht memiliki tiang dan layar terbuka. Siluetnya membentuk や, dibaca 'ya'." },
  "ゆ": { emoji: "🐟", title: "Ikan berenang di akuarium", story: "Seekor ikan berputar di dalam akuarium lalu keluar melalui celah. Jejaknya membentuk ゆ, dibaca 'yu'." },
  "よ": { emoji: "🪀", title: "Yo-yo pada seutas tali", story: "Sebuah yo-yo turun dari tali dan berputar. Tali serta putarannya membentuk よ, dibaca 'yo'." },
  "ら": { emoji: "🐇", title: "Kelinci berlari", story: "Kelinci atau rabbit mengangkat telinga lalu melompat. Jejak lompatannya membentuk ら, dibaca 'ra'." },
  "り": { emoji: "🌿", title: "Dua batang ilalang", story: "Dua batang ilalang berdiri di tepi sungai. Keduanya membentuk り, dibaca 'ri'." },
  "る": { emoji: "🛣️", title: "Rute berakhir di bundaran", story: "Sebuah route turun lalu berputar di bundaran kecil. Jalannya membentuk る, dibaca 'ru'." },
  "れ": { emoji: "🦌", title: "Rusa menarik tali", story: "Seekor reindeer menarik tali panjang yang berkelok. Tali dan tubuhnya membentuk れ, dibaca 're'." },
  "ろ": { emoji: "🛤️", title: "Jalan mengitari blok", story: "Sebuah road berbelok mengitari satu blok. Jalurnya membentuk ろ, dibaca 'ro'." },
  "わ": { emoji: "🌊", title: "Pusaran air", story: "Air atau water mengalir melewati tiang lalu berputar. Alirannya membentuk わ, dibaca 'wa'." },
  "を": { emoji: "🏅", title: "Pelari melewati rintangan", story: "Pelari Olimpiade melewati dua rintangan dan garis akhir melengkung. Jalurnya membentuk を, dibaca 'o'." },
  "ん": { emoji: "👃", title: "Hidung berkata n", story: "Siluet hidung menurun lalu melengkung saat bersuara 'n'. Garis hidungnya membentuk ん." },
};
